### ISSUE TITLE
Please remove Envy Code R

### ISSUE THREAD

**Issue by damieng** [Agezao/CamisasSI-2k15#1]
Please remove Envy Code R, redistribution is not permitted as per the readme.

**Comment by Agezao** [comment]
Hi Damien, sorry for the mistake.
I've already removed the files from the source and have also included references for your blog/website for the ones interested in know more about Envy Code R.
Let me know if there's anything more!

Thanks, best regards!

**Comment by damieng** [comment]
Great, thanks for your understanding.
